var en = {
    remove: "Remove",
    add: "Add",
    back: "Back",
    emailSent: "Email Sent!",
    signIn: "Sign In",
    signin: "sign in",
    signOut: "Sign Out",
    signUp: "Sign Up",
    OR: "OR",
    forgotPassword: "Forgot your password?",
    emailAddress: "Email Address",
    emailResetLink: "Email Reset Link",
    dontHaveAnAccount: "Don't have an account?",
    resetYourPassword: "Reset your password",
    updateYourPassword: "Update your password",
    password: "Password",
    usernameOrEmail: "Username or email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "If you already have an account",
    signUpWithYourEmailAddress: "Sign up with your email address",
    username: "Username",
    optional: "Optional",
    signupCode: "Signup Code",
    clickAgree: "By clicking Sign up, you agree to our",
    privacyPolicy: "Privacy Policy",
    terms: "Terms of Use",
    sign: "Sign",
    configure: "Configure",
    "with": "with",
    createAccount: "Create an Account",
    and: "and",
    "Match failed": "Match failed",
    "User not found": "User not found",
    error: {
        minChar: "7 character minimum password.",
        pwOneLetter: "Password requires 1 letter.",
        pwOneDigit: "Password must have at least one digit.",
        usernameRequired: "Username is required.",
        emailRequired: "Email is required.",
        signupCodeRequired: "Signup code is required.",
        signupCodeIncorrect: "Signup code is incorrect.",
        signInRequired: "You must be signed in to do that.",
        usernameIsEmail: "Username cannot be an email address."
    }
};

T9n.map("en", en);