var fr = {
    add: "Ajoutes",
    back: "Reculer",
    emailSent: "Email Envoyé!",
    signIn: "Se Connecter",
    signin: "se connecter",
    signOut: "Se Deconnecter",
    signUp: "S'enregistrer",
    OR: "OU",
    forgotPassword: "Vous avez oublié votre mot de passe ?",
    emailAddress: "Adresse Email",
    emailResetLink: "Adresse pour reinitialiser votre mot de passe",
    dontHaveAnAccount: "Vous n'avez pas de compte ?",
    resetYourPassword: "Reinitialiser votre mot de passe",
    updateYourPassword: "Mettre à jour le mot de passe",
    password: "Mot de passe",
    usernameOrEmail: "Nom d'utilisateur ou email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Si vous avez déjà un compte",
    signUpWithYourEmailAddress: "S'enregistrer avec votre adresse email",
    username: "Nom d'utilisateur",
    optional: "Optionnel",
    signupCode: "Code d'inscription",
    clickAgree: "En cliquant sur S'enregistrer, vous acceptez notre",
    privacyPolicy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    sign: "S'enregistrer",
    configure: "Configurer",
    "with": "avec",
    createAccount: "Créer un compte",
    and: "et",
    error: {
        minChar: "Votre mot de passe doit contenir au minimum 7 caractères.",
        pwOneLetter: "Votre mot de passe doit contenir au moins une lettre.",
        pwOneDigit: "Votre mot de passe doit contenir au moins un chiffre.",
        usernameRequired: "Un nom d'utilisateur est requis.",
        emailRequired: "Un email est requis.",
        signupCodeRequired: "Un code d'inscription est requis.",
        signupCodeIncorrect: "Le code d'enregistrement est incorrect.",
        signInRequired: "Vous devez être connecté pour continuer.",
        usernameIsEmail: "Le nom d'utilisateur ne peut être le même que l'adresse email."
    }
};

T9n.map("fr", fr);