var de = {
    add: "Anbaust",
    back: "Zurück",
    emailSent: "E-Mail gesendet!",
    signIn: "Anmelden",
    signin: "anmelden",
    signOut: "Abmelden",
    signUp: "Registrieren",
    OR: "ODER",
    forgotPassword: "Passwort vergessen?",
    emailAddress: "E-Mail Adresse",
    emailResetLink: "Senden",
    dontHaveAnAccount: "Noch kein Konto?",
    resetYourPassword: "Passwort zurücksetzen",
    updateYourPassword: "Passwort aktualisieren",
    password: "Passwort",
    usernameOrEmail: "Benutzername oder E-Mail",
    email: "E-Mail",
    ifYouAlreadyHaveAnAccount: "Falls Sie ein Konto haben, bitte hier",
    signUpWithYourEmailAddress: "Mit E-Mail registrieren",
    username: "Benutzername",
    optional: "Optional",
    signupCode: "Registrierungscode",
    clickAgree: "Durch die Registrierung akzeptieren Sie unsere",
    privacyPolicy: "Datenschutzerklärung",
    terms: "Geschäftsbedingungen",
    sign: "Anmelden",
    configure: "Konfigurieren",
    "with": "mit",
    createAccount: "Konto erzeugen",
    and: "und",
    error: {
        minChar: "Passwort muss mindesten 7 Zeichen lang sein.",
        pwOneLetter: "Passwort muss mindestens einen Buchstaben enthalten.",
        pwOneDigit: "Passwort muss mindestens eine Ziffer enthalten.",
        usernameRequired: "Benutzername benötigt.",
        emailRequired: "E-Mail benötigt.",
        signupCodeRequired: "Registrierungscode benötigt.",
        signupCodeIncorrect: "Registrierungscode ungültig.",
        signInRequired: "Sie müssen sich anmelden.",
        usernameIsEmail: "Benutzername kann nicht eine E-Mail."
    }
};

T9n.map("de", de);