var it = {
    remove: "Rimuovi",
    add: "Aggiungi",
    back: "Indietro",
    emailSent: "Email Inviata!",
    signIn: "Accedi",
    signin: "accedi",
    signOut: "Esci",
    signUp: "Registrati",
    OR: "OPPURE",
    forgotPassword: "Hai dimenticato la password?",
    emailAddress: "Indirizzo Email",
    emailResetLink: "Invia Link di Reset",
    dontHaveAnAccount: "Non hai un account?",
    resetYourPassword: "Reimposta la password",
    updateYourPassword: "Aggiorna la password",
    password: "Password",
    usernameOrEmail: "Nome utente o email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Se hai già un account",
    signUpWithYourEmailAddress: "Registrati con il tuo indirizzo email",
    username: "Username",
    optional: "Opzionale",
    signupCode: "Codice di Registrazione",
    clickAgree: "Cliccando Registrati, accetti la nostra",
    privacyPolicy: "Privacy Policy",
    terms: "Termini di Servizio",
    sign: "Accedi",
    configure: "Configura",
    "with": "con",
    createAccount: "Crea un Account",
    and: "e",
    "Match failed": "Riscontro fallito",
    "User not found": "Utente non trovato",
    error: {
        minChar: "Password di almeno 7 caratteri.",
        pwOneLetter: "La Password deve contenere 1 lettera.",
        pwOneDigit: "La Password deve contenere almeno un numero.",
        usernameRequired: "Il Nome utente è obbligatorio.",
        emailRequired: "L'Email è obbligatoria.",
        signupCodeRequired: "Il Codice di Registrazione è obbligatorio.",
        signupCodeIncorrect: "Codice di Registrazione errato.",
        signInRequired: "Per fare questo devi accedere.",
        usernameIsEmail: "Il Nome Utente non può essere un indirizzo email."
    }
};

T9n.map("it", it);