var pl = {
    add: "Dodawać",
    back: "Do tyłu",
    emailSent: "E-mail wysłany!",
    signIn: "Zaloguj się",
    signin: "zaloguj się",
    signOut: "Wyloguj się",
    signUp: "Zarejestruj się",
    OR: "LUB",
    forgotPassword: "Zapomniałeś hasła?",
    emailAddress: "Adres email",
    emailResetLink: "Wyślij email z linkiem do zmiany hasła",
    dontHaveAnAccount: "Nie masz konta?",
    resetYourPassword: "Ustaw nowe hasło",
    updateYourPassword: "Zaktualizuj swoje hasło",
    password: "Hasło",
    usernameOrEmail: "Nazwa użytkownika lub email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Jeżeli już masz konto",
    signUpWithYourEmailAddress: "Zarejestruj się używając adresu email",
    username: "Nazwa użytkownika",
    optional: "Nieobowiązkowe",
    signupCode: "Kod rejestracji",
    clickAgree: "Klikając na Zarejestruj się zgadzasz się z naszą",
    privacyPolicy: "polityką prywatności",
    terms: "warunkami korzystania z serwisu",
    sign: "Podpisz",
    configure: "Konfiguruj",
    "with": "z",
    createAccount: "Utwórz konto",
    and: "i",
    error: {
        minChar: "7 znaków to minimalna długość hasła.",
        pwOneLetter: "Hasło musi zawierać 1 literę.",
        pwOneDigit: "Hasło musi zawierać przynajmniej jedną cyfrę.",
        usernameRequired: "Wymagana jest nazwa użytkownika.",
        emailRequired: "Wymagany jest adres email.",
        signupCodeRequired: "Wymagany jest kod rejestracji.",
        signupCodeIncorrect: "Kod rejestracji jest nieprawidłowy.",
        signInRequired: "Musisz być zalogowany, aby to zrobić.",
        usernameIsEmail: "Nazwa użytkownika nie może być adres e-mail."
    }
};

T9n.map("pl", pl);