var es = {
    add: "Agregar",
    back: "Atrás",
    emailSent: "Email Enviado!",
    signIn: "Entrar",
    signOut: "Salir",
    signUp: "Suscribir",
    OR: "O",
    forgotPassword: "Contraseña olvidada?",
    emailAddress: "Dirección de Email",
    emailResetLink: "Reiniciar Email",
    dontHaveAnAccount: "No tenés una cuenta?",
    resetYourPassword: "Resetear tu contraseña",
    updateYourPassword: "Actualizar tu contraseña",
    password: "Contraseña",
    usernameOrEmail: "Usuario o email",
    email: "Email",
    ifYouAlreadyHaveAnAccount: "Si ya tenés una cuenta",
    signUpWithYourEmailAddress: "Suscribir con tu email",
    username: "Usuario",
    optional: "Opcional",
    signupCode: "Codigo para suscribir",
    clickAgree: "Si haces clic en Sucribir estas de acuerdo con la",
    privacyPolicy: "Póliza de Privacidad",
    terms: "Terminos de Uso",
    sign: "Ingresar",
    configure: "Disposición",
    "with": "con",
    createAccount: "Crear cuenta",
    and: "y",
    error: {
        minChar: "7 carácteres mínimo.",
        pwOneLetter: "mínimo una letra.",
        pwOneDigit: "mínimo un dígito.",
        usernameRequired: "Usuario es necesario.",
        emailRequired: "Email es necesario.",
        signupCodeRequired: "Código para suscribir es necesario.",
        signupCodeIncorrect: "Código para suscribir no coincide.",
        signInRequired: "Debes iniciar sesión para hacer eso.",
        usernameIsEmail: "Usuario no puede ser Email."
    }
};

T9n.map("es", es);